# Generated by Django 4.0.6 on 2023-02-01 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_imgs_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imgs',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
